version: "3.9"

services:
  api-node:
    image: "api-node"
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    init: true
    ports:
      - "4323:4323"
    depends_on:
      - db
      - redis
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - MONGO_URL=${MONGO_URL}
      - ARGON_MEMORY_COST=${ARGON_MEMORY_COST}
      - ARGON_TIME_COST=${ARGON_TIME_COST}
      - ARGON_PARALLELISM=${ARGON_PARALLELISM}
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - NODE_ENV=${NODE_ENV}
      - SWAGGER_USER=${SWAGGER_USER}
      - SWAGGER_PASS=${SWAGGER_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - PORT=${PORT}
      - REDIS_URL=${REDIS_URL}
    restart: unless-stopped

  db:
    image: mongo:8-noble
    ports:
      - "27018:27017"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongo-data:/data/
  redis:
    image: redis:8.4.0
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command:
      - sh
      - -c
      - |
        redis-server --requirepass "$REDIS_PASSWORD"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
